import {
  BarChart3,
  FileText,
  Globe,
  Hotel,
  Link2,
  Sparkles,
  Users,
  UtensilsCrossed,
} from "lucide-react";
import type { PlatformAppDefinition } from "@/types/platform";

export const PLATFORM_APPLICATIONS: PlatformAppDefinition[] = [
  {
    key: "pms",
    title: "Property Management System",
    description:
      "Manage reservations, front desk operations, housekeeping, billing, payments, and guest experiences.",
    icon: Hotel,
    features: ["Reservations", "Front Desk", "Guest Management", "Housekeeping", "Billing", "Reports"],
    route: "/",
    openLabel: "Open PMS",
    status: "active",
    accentClass: "from-primary/15 to-primary/5 border-primary/20",
    anyPermissions: ["dashboard.view"],
  },
  {
    key: "pos",
    title: "Point of Sale",
    description: "Manage restaurant operations, orders, kitchen workflows, billing, and inventory.",
    icon: UtensilsCrossed,
    features: ["Orders", "Menu Management", "KOT", "Billing", "Inventory"],
    route: "/pos",
    openLabel: "Open POS",
    status: "active",
    accentClass: "from-warning/15 to-warning/5 border-warning/25",
    roles: ["super_admin", "owner", "general_manager", "accounts"],
  },
  {
    key: "crm",
    title: "Customer Relationship Management",
    description: "Manage leads, customers, campaigns, and sales activities.",
    icon: Users,
    features: ["Leads", "Contacts", "Opportunities", "Campaigns", "Tasks"],
    route: "/leads",
    openLabel: "Open CRM",
    status: "active",
    accentClass: "from-info/15 to-info/5 border-info/25",
    roles: ["super_admin", "owner", "general_manager", "front_office_manager", "revenue_manager"],
  },
  {
    key: "analytics",
    title: "Analytics & Insights",
    description: "View business performance, KPIs, revenue, occupancy, and customer analytics.",
    icon: BarChart3,
    features: ["Revenue Analytics", "Occupancy Analytics", "Sales Insights", "KPI Dashboard"],
    route: "/analytics/executive",
    openLabel: "Open Analytics",
    status: "active",
    accentClass: "from-success/15 to-success/5 border-success/25",
    anyPermissions: ["analytics.executive", "reports.view", "ai.view"],
  },
  {
    key: "reports",
    title: "Reports Center",
    description: "Access operational, financial, tax, and custom reports.",
    icon: FileText,
    features: ["Occupancy Reports", "Revenue Reports", "GST Reports", "Financial Reports"],
    route: "/reports",
    openLabel: "Open Reports",
    status: "active",
    accentClass: "from-primary/10 to-surface-2 border-border",
    anyPermissions: ["reports.view"],
  },
  {
    key: "channelManager",
    title: "Channel Manager",
    description: "Synchronize inventory, rates, and reservations across OTA channels.",
    icon: Link2,
    features: ["OTA Sync", "Inventory Sync", "Rate Sync", "Mapping"],
    route: "/channel-manager",
    openLabel: "Open Channel Manager",
    status: "coming_soon",
    accentClass: "from-muted/30 to-surface-2 border-border-subtle",
    anyPermissions: ["ota.manage"],
    feature: "channelManager",
  },
  {
    key: "bookingEngine",
    title: "Booking Engine",
    description: "Enable direct bookings from your hotel website.",
    icon: Globe,
    features: ["Direct Booking", "Promotions", "Availability", "Rate Management"],
    route: "/booking-engine",
    openLabel: "Open Booking Engine",
    status: "coming_soon",
    accentClass: "from-muted/30 to-surface-2 border-border-subtle",
    anyPermissions: ["bookingengine.view"],
    feature: "bookingEngine",
  },
  {
    key: "aiHub",
    title: "AI Hub",
    description: "AI-powered assistants and automation tools for hotel operations.",
    icon: Sparkles,
    features: ["AI Concierge", "Revenue Manager", "AI Analytics", "Operations Assistant"],
    route: "/ai-insights",
    openLabel: "Open AI Hub",
    status: "coming_soon",
    accentClass: "from-primary/10 to-surface-2 border-primary/15",
    anyPermissions: ["ai.view", "revenue.aiDashboard"],
    feature: "revenueAi",
  },
  {
    key: "superadmin",
    title: "Superadmin Console",
    description: "Manage tenants, subscriptions, features, and platform-wide settings.",
    icon: Users, // Can reuse Users icon for now or Shield
    features: ["Tenant Management", "Subscription Plans", "Platform Settings"],
    route: "/superadmin/dashboard",
    openLabel: "Open Console",
    status: "active",
    accentClass: "from-primary/20 to-primary/5 border-primary/30",
    roles: ["super_admin"],
  },
];
