/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WebsiteBuilderRouteImport } from './routes/website-builder'
import { Route as UsersRouteImport } from './routes/users'
import { Route as TransportRouteImport } from './routes/transport'
import { Route as TaxesFeesRouteImport } from './routes/taxes-fees'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as StyleguideRouteImport } from './routes/styleguide'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RoomsRouteImport } from './routes/rooms'
import { Route as RolesRouteImport } from './routes/roles'
import { Route as RevenueDrilldownRouteImport } from './routes/revenue-drilldown'
import { Route as RevenueRouteImport } from './routes/revenue'
import { Route as ReservationsRouteImport } from './routes/reservations'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as RegistrationCardsRouteImport } from './routes/registration-cards'
import { Route as RatePlansRouteImport } from './routes/rate-plans'
import { Route as PropertyRouteImport } from './routes/property'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PosRouteImport } from './routes/pos'
import { Route as PmsIntegrationsRouteImport } from './routes/pms-integrations'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as PackagesRouteImport } from './routes/packages'
import { Route as OtaRouteImport } from './routes/ota'
import { Route as OneRouteImport } from './routes/one'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MastersRouteImport } from './routes/masters'
import { Route as MaintenanceRouteImport } from './routes/maintenance'
import { Route as LoyaltyRouteImport } from './routes/loyalty'
import { Route as LostFoundRouteImport } from './routes/lost-found'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LeadsRouteImport } from './routes/leads'
import { Route as HousekeepingRouteImport } from './routes/housekeeping'
import { Route as HotelsRouteImport } from './routes/hotels'
import { Route as GuestsRouteImport } from './routes/guests'
import { Route as GuestRequestsRouteImport } from './routes/guest-requests'
import { Route as GroupsRouteImport } from './routes/groups'
import { Route as FrontDeskRouteImport } from './routes/front-desk'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as CorporateRouteImport } from './routes/corporate'
import { Route as ConciergeRouteImport } from './routes/concierge'
import { Route as CommunicationsRouteImport } from './routes/communications'
import { Route as CheckInRouteImport } from './routes/check-in'
import { Route as ChannelManagerRouteImport } from './routes/channel-manager'
import { Route as BookingReadinessRouteImport } from './routes/booking-readiness'
import { Route as BookingEngineRouteImport } from './routes/booking-engine'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as AvailabilityRouteImport } from './routes/availability'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as AnomalyMonitorRouteImport } from './routes/anomaly-monitor'
import { Route as AiInsightsRouteImport } from './routes/ai-insights'
import { Route as AddOnsRouteImport } from './routes/add-ons'
import { Route as ActivityTimelineRouteImport } from './routes/activity-timeline'
import { Route as ActivitiesRouteImport } from './routes/activities'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SuperadminUsersRouteImport } from './routes/superadmin.users'
import { Route as SuperadminTenantsRouteImport } from './routes/superadmin.tenants'
import { Route as SuperadminSubscriptionsRouteImport } from './routes/superadmin.subscriptions'
import { Route as SuperadminSettingsRouteImport } from './routes/superadmin.settings'
import { Route as SuperadminRolesRouteImport } from './routes/superadmin.roles'
import { Route as SuperadminPropertiesRouteImport } from './routes/superadmin.properties'
import { Route as SuperadminProductsRouteImport } from './routes/superadmin.products'
import { Route as SuperadminManualRouteImport } from './routes/superadmin.manual'
import { Route as SuperadminDashboardRouteImport } from './routes/superadmin.dashboard'
import { Route as RevenueAiDashboardRouteImport } from './routes/revenue.ai-dashboard'
import { Route as ReservationsNewRouteImport } from './routes/reservations.new'
import { Route as PosMenuRouteImport } from './routes/pos.menu'
import { Route as PosKotRouteImport } from './routes/pos.kot'
import { Route as PosInventoryRouteImport } from './routes/pos.inventory'
import { Route as PosBillingRouteImport } from './routes/pos.billing'
import { Route as HousekeepingMobileRouteImport } from './routes/housekeeping.mobile'
import { Route as DashboardMultiPropertyRouteImport } from './routes/dashboard.multi-property'
import { Route as ChannelManagerSyncLogsRouteImport } from './routes/channel-manager.sync-logs'
import { Route as ChannelManagerRoomMappingRouteImport } from './routes/channel-manager.room-mapping'
import { Route as ChannelManagerRoomContentRouteImport } from './routes/channel-manager.room-content'
import { Route as ChannelManagerRevenueRouteImport } from './routes/channel-manager.revenue'
import { Route as ChannelManagerRestrictionsRouteImport } from './routes/channel-manager.restrictions'
import { Route as ChannelManagerReservationsRouteImport } from './routes/channel-manager.reservations'
import { Route as ChannelManagerRatesRouteImport } from './routes/channel-manager.rates'
import { Route as ChannelManagerRatePlansRouteImport } from './routes/channel-manager.rate-plans'
import { Route as ChannelManagerPropertyContentRouteImport } from './routes/channel-manager.property-content'
import { Route as ChannelManagerMultiPropertyRouteImport } from './routes/channel-manager.multi-property'
import { Route as ChannelManagerInventoryRouteImport } from './routes/channel-manager.inventory'
import { Route as ChannelManagerIncidentsRouteImport } from './routes/channel-manager.incidents'
import { Route as ChannelManagerImagesRouteImport } from './routes/channel-manager.images'
import { Route as ChannelManagerConnectionsRouteImport } from './routes/channel-manager.connections'
import { Route as ChannelManagerAvailabilityRouteImport } from './routes/channel-manager.availability'
import { Route as ChannelManagerAnalyticsRouteImport } from './routes/channel-manager.analytics'
import { Route as AnalyticsExecutiveRouteImport } from './routes/analytics.executive'
import { Route as SuperadminTenantsNewRouteImport } from './routes/superadmin.tenants.new'

const WebsiteBuilderRoute = WebsiteBuilderRouteImport.update({
  id: '/website-builder',
  path: '/website-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const TransportRoute = TransportRouteImport.update({
  id: '/transport',
  path: '/transport',
  getParentRoute: () => rootRouteImport,
} as any)
const TaxesFeesRoute = TaxesFeesRouteImport.update({
  id: '/taxes-fees',
  path: '/taxes-fees',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const StyleguideRoute = StyleguideRouteImport.update({
  id: '/styleguide',
  path: '/styleguide',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsRoute = RoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => rootRouteImport,
} as any)
const RolesRoute = RolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const RevenueDrilldownRoute = RevenueDrilldownRouteImport.update({
  id: '/revenue-drilldown',
  path: '/revenue-drilldown',
  getParentRoute: () => rootRouteImport,
} as any)
const RevenueRoute = RevenueRouteImport.update({
  id: '/revenue',
  path: '/revenue',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservationsRoute = ReservationsRouteImport.update({
  id: '/reservations',
  path: '/reservations',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistrationCardsRoute = RegistrationCardsRouteImport.update({
  id: '/registration-cards',
  path: '/registration-cards',
  getParentRoute: () => rootRouteImport,
} as any)
const RatePlansRoute = RatePlansRouteImport.update({
  id: '/rate-plans',
  path: '/rate-plans',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertyRoute = PropertyRouteImport.update({
  id: '/property',
  path: '/property',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PosRoute = PosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => rootRouteImport,
} as any)
const PmsIntegrationsRoute = PmsIntegrationsRouteImport.update({
  id: '/pms-integrations',
  path: '/pms-integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesRoute = PackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const OtaRoute = OtaRouteImport.update({
  id: '/ota',
  path: '/ota',
  getParentRoute: () => rootRouteImport,
} as any)
const OneRoute = OneRouteImport.update({
  id: '/one',
  path: '/one',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MastersRoute = MastersRouteImport.update({
  id: '/masters',
  path: '/masters',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceRoute = MaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const LoyaltyRoute = LoyaltyRouteImport.update({
  id: '/loyalty',
  path: '/loyalty',
  getParentRoute: () => rootRouteImport,
} as any)
const LostFoundRoute = LostFoundRouteImport.update({
  id: '/lost-found',
  path: '/lost-found',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsRoute = LeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const HousekeepingRoute = HousekeepingRouteImport.update({
  id: '/housekeeping',
  path: '/housekeeping',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelsRoute = HotelsRouteImport.update({
  id: '/hotels',
  path: '/hotels',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestsRoute = GuestsRouteImport.update({
  id: '/guests',
  path: '/guests',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestRequestsRoute = GuestRequestsRouteImport.update({
  id: '/guest-requests',
  path: '/guest-requests',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsRoute = GroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => rootRouteImport,
} as any)
const FrontDeskRoute = FrontDeskRouteImport.update({
  id: '/front-desk',
  path: '/front-desk',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const CorporateRoute = CorporateRouteImport.update({
  id: '/corporate',
  path: '/corporate',
  getParentRoute: () => rootRouteImport,
} as any)
const ConciergeRoute = ConciergeRouteImport.update({
  id: '/concierge',
  path: '/concierge',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunicationsRoute = CommunicationsRouteImport.update({
  id: '/communications',
  path: '/communications',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckInRoute = CheckInRouteImport.update({
  id: '/check-in',
  path: '/check-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ChannelManagerRoute = ChannelManagerRouteImport.update({
  id: '/channel-manager',
  path: '/channel-manager',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingReadinessRoute = BookingReadinessRouteImport.update({
  id: '/booking-readiness',
  path: '/booking-readiness',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingEngineRoute = BookingEngineRouteImport.update({
  id: '/booking-engine',
  path: '/booking-engine',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const AvailabilityRoute = AvailabilityRouteImport.update({
  id: '/availability',
  path: '/availability',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AnomalyMonitorRoute = AnomalyMonitorRouteImport.update({
  id: '/anomaly-monitor',
  path: '/anomaly-monitor',
  getParentRoute: () => rootRouteImport,
} as any)
const AiInsightsRoute = AiInsightsRouteImport.update({
  id: '/ai-insights',
  path: '/ai-insights',
  getParentRoute: () => rootRouteImport,
} as any)
const AddOnsRoute = AddOnsRouteImport.update({
  id: '/add-ons',
  path: '/add-ons',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityTimelineRoute = ActivityTimelineRouteImport.update({
  id: '/activity-timeline',
  path: '/activity-timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitiesRoute = ActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminUsersRoute = SuperadminUsersRouteImport.update({
  id: '/superadmin/users',
  path: '/superadmin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminTenantsRoute = SuperadminTenantsRouteImport.update({
  id: '/superadmin/tenants',
  path: '/superadmin/tenants',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminSubscriptionsRoute = SuperadminSubscriptionsRouteImport.update({
  id: '/superadmin/subscriptions',
  path: '/superadmin/subscriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminSettingsRoute = SuperadminSettingsRouteImport.update({
  id: '/superadmin/settings',
  path: '/superadmin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminRolesRoute = SuperadminRolesRouteImport.update({
  id: '/superadmin/roles',
  path: '/superadmin/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminPropertiesRoute = SuperadminPropertiesRouteImport.update({
  id: '/superadmin/properties',
  path: '/superadmin/properties',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminProductsRoute = SuperadminProductsRouteImport.update({
  id: '/superadmin/products',
  path: '/superadmin/products',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminManualRoute = SuperadminManualRouteImport.update({
  id: '/superadmin/manual',
  path: '/superadmin/manual',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminDashboardRoute = SuperadminDashboardRouteImport.update({
  id: '/superadmin/dashboard',
  path: '/superadmin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const RevenueAiDashboardRoute = RevenueAiDashboardRouteImport.update({
  id: '/ai-dashboard',
  path: '/ai-dashboard',
  getParentRoute: () => RevenueRoute,
} as any)
const ReservationsNewRoute = ReservationsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ReservationsRoute,
} as any)
const PosMenuRoute = PosMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => PosRoute,
} as any)
const PosKotRoute = PosKotRouteImport.update({
  id: '/kot',
  path: '/kot',
  getParentRoute: () => PosRoute,
} as any)
const PosInventoryRoute = PosInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => PosRoute,
} as any)
const PosBillingRoute = PosBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => PosRoute,
} as any)
const HousekeepingMobileRoute = HousekeepingMobileRouteImport.update({
  id: '/mobile',
  path: '/mobile',
  getParentRoute: () => HousekeepingRoute,
} as any)
const DashboardMultiPropertyRoute = DashboardMultiPropertyRouteImport.update({
  id: '/dashboard/multi-property',
  path: '/dashboard/multi-property',
  getParentRoute: () => rootRouteImport,
} as any)
const ChannelManagerSyncLogsRoute = ChannelManagerSyncLogsRouteImport.update({
  id: '/sync-logs',
  path: '/sync-logs',
  getParentRoute: () => ChannelManagerRoute,
} as any)
const ChannelManagerRoomMappingRoute =
  ChannelManagerRoomMappingRouteImport.update({
    id: '/room-mapping',
    path: '/room-mapping',
    getParentRoute: () => ChannelManagerRoute,
  } as any)
const ChannelManagerRoomContentRoute =
  ChannelManagerRoomContentRouteImport.update({
    id: '/room-content',
    path: '/room-content',
    getParentRoute: () => ChannelManagerRoute,
  } as any)
const ChannelManagerRevenueRoute = ChannelManagerRevenueRouteImport.update({
  id: '/revenue',
  path: '/revenue',
  getParentRoute: () => ChannelManagerRoute,
} as any)
const ChannelManagerRestrictionsRoute =
  ChannelManagerRestrictionsRouteImport.update({
    id: '/restrictions',
    path: '/restrictions',
    getParentRoute: () => ChannelManagerRoute,
  } as any)
const ChannelManagerReservationsRoute =
  ChannelManagerReservationsRouteImport.update({
    id: '/reservations',
    path: '/reservations',
    getParentRoute: () => ChannelManagerRoute,
  } as any)
const ChannelManagerRatesRoute = ChannelManagerRatesRouteImport.update({
  id: '/rates',
  path: '/rates',
  getParentRoute: () => ChannelManagerRoute,
} as any)
const ChannelManagerRatePlansRoute = ChannelManagerRatePlansRouteImport.update({
  id: '/rate-plans',
  path: '/rate-plans',
  getParentRoute: () => ChannelManagerRoute,
} as any)
const ChannelManagerPropertyContentRoute =
  ChannelManagerPropertyContentRouteImport.update({
    id: '/property-content',
    path: '/property-content',
    getParentRoute: () => ChannelManagerRoute,
  } as any)
const ChannelManagerMultiPropertyRoute =
  ChannelManagerMultiPropertyRouteImport.update({
    id: '/multi-property',
    path: '/multi-property',
    getParentRoute: () => ChannelManagerRoute,
  } as any)
const ChannelManagerInventoryRoute = ChannelManagerInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => ChannelManagerRoute,
} as any)
const ChannelManagerIncidentsRoute = ChannelManagerIncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => ChannelManagerRoute,
} as any)
const ChannelManagerImagesRoute = ChannelManagerImagesRouteImport.update({
  id: '/images',
  path: '/images',
  getParentRoute: () => ChannelManagerRoute,
} as any)
const ChannelManagerConnectionsRoute =
  ChannelManagerConnectionsRouteImport.update({
    id: '/connections',
    path: '/connections',
    getParentRoute: () => ChannelManagerRoute,
  } as any)
const ChannelManagerAvailabilityRoute =
  ChannelManagerAvailabilityRouteImport.update({
    id: '/availability',
    path: '/availability',
    getParentRoute: () => ChannelManagerRoute,
  } as any)
const ChannelManagerAnalyticsRoute = ChannelManagerAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => ChannelManagerRoute,
} as any)
const AnalyticsExecutiveRoute = AnalyticsExecutiveRouteImport.update({
  id: '/analytics/executive',
  path: '/analytics/executive',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminTenantsNewRoute = SuperadminTenantsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => SuperadminTenantsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRoute
  '/activity-timeline': typeof ActivityTimelineRoute
  '/add-ons': typeof AddOnsRoute
  '/ai-insights': typeof AiInsightsRoute
  '/anomaly-monitor': typeof AnomalyMonitorRoute
  '/audit': typeof AuditRoute
  '/availability': typeof AvailabilityRoute
  '/billing': typeof BillingRoute
  '/booking-engine': typeof BookingEngineRoute
  '/booking-readiness': typeof BookingReadinessRoute
  '/channel-manager': typeof ChannelManagerRouteWithChildren
  '/check-in': typeof CheckInRoute
  '/communications': typeof CommunicationsRoute
  '/concierge': typeof ConciergeRoute
  '/corporate': typeof CorporateRoute
  '/feedback': typeof FeedbackRoute
  '/front-desk': typeof FrontDeskRoute
  '/groups': typeof GroupsRoute
  '/guest-requests': typeof GuestRequestsRoute
  '/guests': typeof GuestsRoute
  '/hotels': typeof HotelsRoute
  '/housekeeping': typeof HousekeepingRouteWithChildren
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/lost-found': typeof LostFoundRoute
  '/loyalty': typeof LoyaltyRoute
  '/maintenance': typeof MaintenanceRoute
  '/masters': typeof MastersRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/one': typeof OneRoute
  '/ota': typeof OtaRoute
  '/packages': typeof PackagesRoute
  '/payments': typeof PaymentsRoute
  '/pms-integrations': typeof PmsIntegrationsRoute
  '/pos': typeof PosRouteWithChildren
  '/pricing': typeof PricingRoute
  '/property': typeof PropertyRoute
  '/rate-plans': typeof RatePlansRoute
  '/registration-cards': typeof RegistrationCardsRoute
  '/reports': typeof ReportsRoute
  '/reservations': typeof ReservationsRouteWithChildren
  '/revenue': typeof RevenueRouteWithChildren
  '/revenue-drilldown': typeof RevenueDrilldownRoute
  '/roles': typeof RolesRoute
  '/rooms': typeof RoomsRoute
  '/search': typeof SearchRoute
  '/services': typeof ServicesRoute
  '/settings': typeof SettingsRoute
  '/staff': typeof StaffRoute
  '/styleguide': typeof StyleguideRoute
  '/tasks': typeof TasksRoute
  '/taxes-fees': typeof TaxesFeesRoute
  '/transport': typeof TransportRoute
  '/users': typeof UsersRoute
  '/website-builder': typeof WebsiteBuilderRoute
  '/analytics/executive': typeof AnalyticsExecutiveRoute
  '/channel-manager/analytics': typeof ChannelManagerAnalyticsRoute
  '/channel-manager/availability': typeof ChannelManagerAvailabilityRoute
  '/channel-manager/connections': typeof ChannelManagerConnectionsRoute
  '/channel-manager/images': typeof ChannelManagerImagesRoute
  '/channel-manager/incidents': typeof ChannelManagerIncidentsRoute
  '/channel-manager/inventory': typeof ChannelManagerInventoryRoute
  '/channel-manager/multi-property': typeof ChannelManagerMultiPropertyRoute
  '/channel-manager/property-content': typeof ChannelManagerPropertyContentRoute
  '/channel-manager/rate-plans': typeof ChannelManagerRatePlansRoute
  '/channel-manager/rates': typeof ChannelManagerRatesRoute
  '/channel-manager/reservations': typeof ChannelManagerReservationsRoute
  '/channel-manager/restrictions': typeof ChannelManagerRestrictionsRoute
  '/channel-manager/revenue': typeof ChannelManagerRevenueRoute
  '/channel-manager/room-content': typeof ChannelManagerRoomContentRoute
  '/channel-manager/room-mapping': typeof ChannelManagerRoomMappingRoute
  '/channel-manager/sync-logs': typeof ChannelManagerSyncLogsRoute
  '/dashboard/multi-property': typeof DashboardMultiPropertyRoute
  '/housekeeping/mobile': typeof HousekeepingMobileRoute
  '/pos/billing': typeof PosBillingRoute
  '/pos/inventory': typeof PosInventoryRoute
  '/pos/kot': typeof PosKotRoute
  '/pos/menu': typeof PosMenuRoute
  '/reservations/new': typeof ReservationsNewRoute
  '/revenue/ai-dashboard': typeof RevenueAiDashboardRoute
  '/superadmin/dashboard': typeof SuperadminDashboardRoute
  '/superadmin/manual': typeof SuperadminManualRoute
  '/superadmin/products': typeof SuperadminProductsRoute
  '/superadmin/properties': typeof SuperadminPropertiesRoute
  '/superadmin/roles': typeof SuperadminRolesRoute
  '/superadmin/settings': typeof SuperadminSettingsRoute
  '/superadmin/subscriptions': typeof SuperadminSubscriptionsRoute
  '/superadmin/tenants': typeof SuperadminTenantsRouteWithChildren
  '/superadmin/users': typeof SuperadminUsersRoute
  '/superadmin/tenants/new': typeof SuperadminTenantsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRoute
  '/activity-timeline': typeof ActivityTimelineRoute
  '/add-ons': typeof AddOnsRoute
  '/ai-insights': typeof AiInsightsRoute
  '/anomaly-monitor': typeof AnomalyMonitorRoute
  '/audit': typeof AuditRoute
  '/availability': typeof AvailabilityRoute
  '/billing': typeof BillingRoute
  '/booking-engine': typeof BookingEngineRoute
  '/booking-readiness': typeof BookingReadinessRoute
  '/channel-manager': typeof ChannelManagerRouteWithChildren
  '/check-in': typeof CheckInRoute
  '/communications': typeof CommunicationsRoute
  '/concierge': typeof ConciergeRoute
  '/corporate': typeof CorporateRoute
  '/feedback': typeof FeedbackRoute
  '/front-desk': typeof FrontDeskRoute
  '/groups': typeof GroupsRoute
  '/guest-requests': typeof GuestRequestsRoute
  '/guests': typeof GuestsRoute
  '/hotels': typeof HotelsRoute
  '/housekeeping': typeof HousekeepingRouteWithChildren
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/lost-found': typeof LostFoundRoute
  '/loyalty': typeof LoyaltyRoute
  '/maintenance': typeof MaintenanceRoute
  '/masters': typeof MastersRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/one': typeof OneRoute
  '/ota': typeof OtaRoute
  '/packages': typeof PackagesRoute
  '/payments': typeof PaymentsRoute
  '/pms-integrations': typeof PmsIntegrationsRoute
  '/pos': typeof PosRouteWithChildren
  '/pricing': typeof PricingRoute
  '/property': typeof PropertyRoute
  '/rate-plans': typeof RatePlansRoute
  '/registration-cards': typeof RegistrationCardsRoute
  '/reports': typeof ReportsRoute
  '/reservations': typeof ReservationsRouteWithChildren
  '/revenue': typeof RevenueRouteWithChildren
  '/revenue-drilldown': typeof RevenueDrilldownRoute
  '/roles': typeof RolesRoute
  '/rooms': typeof RoomsRoute
  '/search': typeof SearchRoute
  '/services': typeof ServicesRoute
  '/settings': typeof SettingsRoute
  '/staff': typeof StaffRoute
  '/styleguide': typeof StyleguideRoute
  '/tasks': typeof TasksRoute
  '/taxes-fees': typeof TaxesFeesRoute
  '/transport': typeof TransportRoute
  '/users': typeof UsersRoute
  '/website-builder': typeof WebsiteBuilderRoute
  '/analytics/executive': typeof AnalyticsExecutiveRoute
  '/channel-manager/analytics': typeof ChannelManagerAnalyticsRoute
  '/channel-manager/availability': typeof ChannelManagerAvailabilityRoute
  '/channel-manager/connections': typeof ChannelManagerConnectionsRoute
  '/channel-manager/images': typeof ChannelManagerImagesRoute
  '/channel-manager/incidents': typeof ChannelManagerIncidentsRoute
  '/channel-manager/inventory': typeof ChannelManagerInventoryRoute
  '/channel-manager/multi-property': typeof ChannelManagerMultiPropertyRoute
  '/channel-manager/property-content': typeof ChannelManagerPropertyContentRoute
  '/channel-manager/rate-plans': typeof ChannelManagerRatePlansRoute
  '/channel-manager/rates': typeof ChannelManagerRatesRoute
  '/channel-manager/reservations': typeof ChannelManagerReservationsRoute
  '/channel-manager/restrictions': typeof ChannelManagerRestrictionsRoute
  '/channel-manager/revenue': typeof ChannelManagerRevenueRoute
  '/channel-manager/room-content': typeof ChannelManagerRoomContentRoute
  '/channel-manager/room-mapping': typeof ChannelManagerRoomMappingRoute
  '/channel-manager/sync-logs': typeof ChannelManagerSyncLogsRoute
  '/dashboard/multi-property': typeof DashboardMultiPropertyRoute
  '/housekeeping/mobile': typeof HousekeepingMobileRoute
  '/pos/billing': typeof PosBillingRoute
  '/pos/inventory': typeof PosInventoryRoute
  '/pos/kot': typeof PosKotRoute
  '/pos/menu': typeof PosMenuRoute
  '/reservations/new': typeof ReservationsNewRoute
  '/revenue/ai-dashboard': typeof RevenueAiDashboardRoute
  '/superadmin/dashboard': typeof SuperadminDashboardRoute
  '/superadmin/manual': typeof SuperadminManualRoute
  '/superadmin/products': typeof SuperadminProductsRoute
  '/superadmin/properties': typeof SuperadminPropertiesRoute
  '/superadmin/roles': typeof SuperadminRolesRoute
  '/superadmin/settings': typeof SuperadminSettingsRoute
  '/superadmin/subscriptions': typeof SuperadminSubscriptionsRoute
  '/superadmin/tenants': typeof SuperadminTenantsRouteWithChildren
  '/superadmin/users': typeof SuperadminUsersRoute
  '/superadmin/tenants/new': typeof SuperadminTenantsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRoute
  '/activity-timeline': typeof ActivityTimelineRoute
  '/add-ons': typeof AddOnsRoute
  '/ai-insights': typeof AiInsightsRoute
  '/anomaly-monitor': typeof AnomalyMonitorRoute
  '/audit': typeof AuditRoute
  '/availability': typeof AvailabilityRoute
  '/billing': typeof BillingRoute
  '/booking-engine': typeof BookingEngineRoute
  '/booking-readiness': typeof BookingReadinessRoute
  '/channel-manager': typeof ChannelManagerRouteWithChildren
  '/check-in': typeof CheckInRoute
  '/communications': typeof CommunicationsRoute
  '/concierge': typeof ConciergeRoute
  '/corporate': typeof CorporateRoute
  '/feedback': typeof FeedbackRoute
  '/front-desk': typeof FrontDeskRoute
  '/groups': typeof GroupsRoute
  '/guest-requests': typeof GuestRequestsRoute
  '/guests': typeof GuestsRoute
  '/hotels': typeof HotelsRoute
  '/housekeeping': typeof HousekeepingRouteWithChildren
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/lost-found': typeof LostFoundRoute
  '/loyalty': typeof LoyaltyRoute
  '/maintenance': typeof MaintenanceRoute
  '/masters': typeof MastersRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/one': typeof OneRoute
  '/ota': typeof OtaRoute
  '/packages': typeof PackagesRoute
  '/payments': typeof PaymentsRoute
  '/pms-integrations': typeof PmsIntegrationsRoute
  '/pos': typeof PosRouteWithChildren
  '/pricing': typeof PricingRoute
  '/property': typeof PropertyRoute
  '/rate-plans': typeof RatePlansRoute
  '/registration-cards': typeof RegistrationCardsRoute
  '/reports': typeof ReportsRoute
  '/reservations': typeof ReservationsRouteWithChildren
  '/revenue': typeof RevenueRouteWithChildren
  '/revenue-drilldown': typeof RevenueDrilldownRoute
  '/roles': typeof RolesRoute
  '/rooms': typeof RoomsRoute
  '/search': typeof SearchRoute
  '/services': typeof ServicesRoute
  '/settings': typeof SettingsRoute
  '/staff': typeof StaffRoute
  '/styleguide': typeof StyleguideRoute
  '/tasks': typeof TasksRoute
  '/taxes-fees': typeof TaxesFeesRoute
  '/transport': typeof TransportRoute
  '/users': typeof UsersRoute
  '/website-builder': typeof WebsiteBuilderRoute
  '/analytics/executive': typeof AnalyticsExecutiveRoute
  '/channel-manager/analytics': typeof ChannelManagerAnalyticsRoute
  '/channel-manager/availability': typeof ChannelManagerAvailabilityRoute
  '/channel-manager/connections': typeof ChannelManagerConnectionsRoute
  '/channel-manager/images': typeof ChannelManagerImagesRoute
  '/channel-manager/incidents': typeof ChannelManagerIncidentsRoute
  '/channel-manager/inventory': typeof ChannelManagerInventoryRoute
  '/channel-manager/multi-property': typeof ChannelManagerMultiPropertyRoute
  '/channel-manager/property-content': typeof ChannelManagerPropertyContentRoute
  '/channel-manager/rate-plans': typeof ChannelManagerRatePlansRoute
  '/channel-manager/rates': typeof ChannelManagerRatesRoute
  '/channel-manager/reservations': typeof ChannelManagerReservationsRoute
  '/channel-manager/restrictions': typeof ChannelManagerRestrictionsRoute
  '/channel-manager/revenue': typeof ChannelManagerRevenueRoute
  '/channel-manager/room-content': typeof ChannelManagerRoomContentRoute
  '/channel-manager/room-mapping': typeof ChannelManagerRoomMappingRoute
  '/channel-manager/sync-logs': typeof ChannelManagerSyncLogsRoute
  '/dashboard/multi-property': typeof DashboardMultiPropertyRoute
  '/housekeeping/mobile': typeof HousekeepingMobileRoute
  '/pos/billing': typeof PosBillingRoute
  '/pos/inventory': typeof PosInventoryRoute
  '/pos/kot': typeof PosKotRoute
  '/pos/menu': typeof PosMenuRoute
  '/reservations/new': typeof ReservationsNewRoute
  '/revenue/ai-dashboard': typeof RevenueAiDashboardRoute
  '/superadmin/dashboard': typeof SuperadminDashboardRoute
  '/superadmin/manual': typeof SuperadminManualRoute
  '/superadmin/products': typeof SuperadminProductsRoute
  '/superadmin/properties': typeof SuperadminPropertiesRoute
  '/superadmin/roles': typeof SuperadminRolesRoute
  '/superadmin/settings': typeof SuperadminSettingsRoute
  '/superadmin/subscriptions': typeof SuperadminSubscriptionsRoute
  '/superadmin/tenants': typeof SuperadminTenantsRouteWithChildren
  '/superadmin/users': typeof SuperadminUsersRoute
  '/superadmin/tenants/new': typeof SuperadminTenantsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activities'
    | '/activity-timeline'
    | '/add-ons'
    | '/ai-insights'
    | '/anomaly-monitor'
    | '/audit'
    | '/availability'
    | '/billing'
    | '/booking-engine'
    | '/booking-readiness'
    | '/channel-manager'
    | '/check-in'
    | '/communications'
    | '/concierge'
    | '/corporate'
    | '/feedback'
    | '/front-desk'
    | '/groups'
    | '/guest-requests'
    | '/guests'
    | '/hotels'
    | '/housekeeping'
    | '/leads'
    | '/login'
    | '/lost-found'
    | '/loyalty'
    | '/maintenance'
    | '/masters'
    | '/notifications'
    | '/onboarding'
    | '/one'
    | '/ota'
    | '/packages'
    | '/payments'
    | '/pms-integrations'
    | '/pos'
    | '/pricing'
    | '/property'
    | '/rate-plans'
    | '/registration-cards'
    | '/reports'
    | '/reservations'
    | '/revenue'
    | '/revenue-drilldown'
    | '/roles'
    | '/rooms'
    | '/search'
    | '/services'
    | '/settings'
    | '/staff'
    | '/styleguide'
    | '/tasks'
    | '/taxes-fees'
    | '/transport'
    | '/users'
    | '/website-builder'
    | '/analytics/executive'
    | '/channel-manager/analytics'
    | '/channel-manager/availability'
    | '/channel-manager/connections'
    | '/channel-manager/images'
    | '/channel-manager/incidents'
    | '/channel-manager/inventory'
    | '/channel-manager/multi-property'
    | '/channel-manager/property-content'
    | '/channel-manager/rate-plans'
    | '/channel-manager/rates'
    | '/channel-manager/reservations'
    | '/channel-manager/restrictions'
    | '/channel-manager/revenue'
    | '/channel-manager/room-content'
    | '/channel-manager/room-mapping'
    | '/channel-manager/sync-logs'
    | '/dashboard/multi-property'
    | '/housekeeping/mobile'
    | '/pos/billing'
    | '/pos/inventory'
    | '/pos/kot'
    | '/pos/menu'
    | '/reservations/new'
    | '/revenue/ai-dashboard'
    | '/superadmin/dashboard'
    | '/superadmin/manual'
    | '/superadmin/products'
    | '/superadmin/properties'
    | '/superadmin/roles'
    | '/superadmin/settings'
    | '/superadmin/subscriptions'
    | '/superadmin/tenants'
    | '/superadmin/users'
    | '/superadmin/tenants/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activities'
    | '/activity-timeline'
    | '/add-ons'
    | '/ai-insights'
    | '/anomaly-monitor'
    | '/audit'
    | '/availability'
    | '/billing'
    | '/booking-engine'
    | '/booking-readiness'
    | '/channel-manager'
    | '/check-in'
    | '/communications'
    | '/concierge'
    | '/corporate'
    | '/feedback'
    | '/front-desk'
    | '/groups'
    | '/guest-requests'
    | '/guests'
    | '/hotels'
    | '/housekeeping'
    | '/leads'
    | '/login'
    | '/lost-found'
    | '/loyalty'
    | '/maintenance'
    | '/masters'
    | '/notifications'
    | '/onboarding'
    | '/one'
    | '/ota'
    | '/packages'
    | '/payments'
    | '/pms-integrations'
    | '/pos'
    | '/pricing'
    | '/property'
    | '/rate-plans'
    | '/registration-cards'
    | '/reports'
    | '/reservations'
    | '/revenue'
    | '/revenue-drilldown'
    | '/roles'
    | '/rooms'
    | '/search'
    | '/services'
    | '/settings'
    | '/staff'
    | '/styleguide'
    | '/tasks'
    | '/taxes-fees'
    | '/transport'
    | '/users'
    | '/website-builder'
    | '/analytics/executive'
    | '/channel-manager/analytics'
    | '/channel-manager/availability'
    | '/channel-manager/connections'
    | '/channel-manager/images'
    | '/channel-manager/incidents'
    | '/channel-manager/inventory'
    | '/channel-manager/multi-property'
    | '/channel-manager/property-content'
    | '/channel-manager/rate-plans'
    | '/channel-manager/rates'
    | '/channel-manager/reservations'
    | '/channel-manager/restrictions'
    | '/channel-manager/revenue'
    | '/channel-manager/room-content'
    | '/channel-manager/room-mapping'
    | '/channel-manager/sync-logs'
    | '/dashboard/multi-property'
    | '/housekeeping/mobile'
    | '/pos/billing'
    | '/pos/inventory'
    | '/pos/kot'
    | '/pos/menu'
    | '/reservations/new'
    | '/revenue/ai-dashboard'
    | '/superadmin/dashboard'
    | '/superadmin/manual'
    | '/superadmin/products'
    | '/superadmin/properties'
    | '/superadmin/roles'
    | '/superadmin/settings'
    | '/superadmin/subscriptions'
    | '/superadmin/tenants'
    | '/superadmin/users'
    | '/superadmin/tenants/new'
  id:
    | '__root__'
    | '/'
    | '/activities'
    | '/activity-timeline'
    | '/add-ons'
    | '/ai-insights'
    | '/anomaly-monitor'
    | '/audit'
    | '/availability'
    | '/billing'
    | '/booking-engine'
    | '/booking-readiness'
    | '/channel-manager'
    | '/check-in'
    | '/communications'
    | '/concierge'
    | '/corporate'
    | '/feedback'
    | '/front-desk'
    | '/groups'
    | '/guest-requests'
    | '/guests'
    | '/hotels'
    | '/housekeeping'
    | '/leads'
    | '/login'
    | '/lost-found'
    | '/loyalty'
    | '/maintenance'
    | '/masters'
    | '/notifications'
    | '/onboarding'
    | '/one'
    | '/ota'
    | '/packages'
    | '/payments'
    | '/pms-integrations'
    | '/pos'
    | '/pricing'
    | '/property'
    | '/rate-plans'
    | '/registration-cards'
    | '/reports'
    | '/reservations'
    | '/revenue'
    | '/revenue-drilldown'
    | '/roles'
    | '/rooms'
    | '/search'
    | '/services'
    | '/settings'
    | '/staff'
    | '/styleguide'
    | '/tasks'
    | '/taxes-fees'
    | '/transport'
    | '/users'
    | '/website-builder'
    | '/analytics/executive'
    | '/channel-manager/analytics'
    | '/channel-manager/availability'
    | '/channel-manager/connections'
    | '/channel-manager/images'
    | '/channel-manager/incidents'
    | '/channel-manager/inventory'
    | '/channel-manager/multi-property'
    | '/channel-manager/property-content'
    | '/channel-manager/rate-plans'
    | '/channel-manager/rates'
    | '/channel-manager/reservations'
    | '/channel-manager/restrictions'
    | '/channel-manager/revenue'
    | '/channel-manager/room-content'
    | '/channel-manager/room-mapping'
    | '/channel-manager/sync-logs'
    | '/dashboard/multi-property'
    | '/housekeeping/mobile'
    | '/pos/billing'
    | '/pos/inventory'
    | '/pos/kot'
    | '/pos/menu'
    | '/reservations/new'
    | '/revenue/ai-dashboard'
    | '/superadmin/dashboard'
    | '/superadmin/manual'
    | '/superadmin/products'
    | '/superadmin/properties'
    | '/superadmin/roles'
    | '/superadmin/settings'
    | '/superadmin/subscriptions'
    | '/superadmin/tenants'
    | '/superadmin/users'
    | '/superadmin/tenants/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivitiesRoute: typeof ActivitiesRoute
  ActivityTimelineRoute: typeof ActivityTimelineRoute
  AddOnsRoute: typeof AddOnsRoute
  AiInsightsRoute: typeof AiInsightsRoute
  AnomalyMonitorRoute: typeof AnomalyMonitorRoute
  AuditRoute: typeof AuditRoute
  AvailabilityRoute: typeof AvailabilityRoute
  BillingRoute: typeof BillingRoute
  BookingEngineRoute: typeof BookingEngineRoute
  BookingReadinessRoute: typeof BookingReadinessRoute
  ChannelManagerRoute: typeof ChannelManagerRouteWithChildren
  CheckInRoute: typeof CheckInRoute
  CommunicationsRoute: typeof CommunicationsRoute
  ConciergeRoute: typeof ConciergeRoute
  CorporateRoute: typeof CorporateRoute
  FeedbackRoute: typeof FeedbackRoute
  FrontDeskRoute: typeof FrontDeskRoute
  GroupsRoute: typeof GroupsRoute
  GuestRequestsRoute: typeof GuestRequestsRoute
  GuestsRoute: typeof GuestsRoute
  HotelsRoute: typeof HotelsRoute
  HousekeepingRoute: typeof HousekeepingRouteWithChildren
  LeadsRoute: typeof LeadsRoute
  LoginRoute: typeof LoginRoute
  LostFoundRoute: typeof LostFoundRoute
  LoyaltyRoute: typeof LoyaltyRoute
  MaintenanceRoute: typeof MaintenanceRoute
  MastersRoute: typeof MastersRoute
  NotificationsRoute: typeof NotificationsRoute
  OnboardingRoute: typeof OnboardingRoute
  OneRoute: typeof OneRoute
  OtaRoute: typeof OtaRoute
  PackagesRoute: typeof PackagesRoute
  PaymentsRoute: typeof PaymentsRoute
  PmsIntegrationsRoute: typeof PmsIntegrationsRoute
  PosRoute: typeof PosRouteWithChildren
  PricingRoute: typeof PricingRoute
  PropertyRoute: typeof PropertyRoute
  RatePlansRoute: typeof RatePlansRoute
  RegistrationCardsRoute: typeof RegistrationCardsRoute
  ReportsRoute: typeof ReportsRoute
  ReservationsRoute: typeof ReservationsRouteWithChildren
  RevenueRoute: typeof RevenueRouteWithChildren
  RevenueDrilldownRoute: typeof RevenueDrilldownRoute
  RolesRoute: typeof RolesRoute
  RoomsRoute: typeof RoomsRoute
  SearchRoute: typeof SearchRoute
  ServicesRoute: typeof ServicesRoute
  SettingsRoute: typeof SettingsRoute
  StaffRoute: typeof StaffRoute
  StyleguideRoute: typeof StyleguideRoute
  TasksRoute: typeof TasksRoute
  TaxesFeesRoute: typeof TaxesFeesRoute
  TransportRoute: typeof TransportRoute
  UsersRoute: typeof UsersRoute
  WebsiteBuilderRoute: typeof WebsiteBuilderRoute
  AnalyticsExecutiveRoute: typeof AnalyticsExecutiveRoute
  DashboardMultiPropertyRoute: typeof DashboardMultiPropertyRoute
  SuperadminDashboardRoute: typeof SuperadminDashboardRoute
  SuperadminManualRoute: typeof SuperadminManualRoute
  SuperadminProductsRoute: typeof SuperadminProductsRoute
  SuperadminPropertiesRoute: typeof SuperadminPropertiesRoute
  SuperadminRolesRoute: typeof SuperadminRolesRoute
  SuperadminSettingsRoute: typeof SuperadminSettingsRoute
  SuperadminSubscriptionsRoute: typeof SuperadminSubscriptionsRoute
  SuperadminTenantsRoute: typeof SuperadminTenantsRouteWithChildren
  SuperadminUsersRoute: typeof SuperadminUsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/website-builder': {
      id: '/website-builder'
      path: '/website-builder'
      fullPath: '/website-builder'
      preLoaderRoute: typeof WebsiteBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transport': {
      id: '/transport'
      path: '/transport'
      fullPath: '/transport'
      preLoaderRoute: typeof TransportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/taxes-fees': {
      id: '/taxes-fees'
      path: '/taxes-fees'
      fullPath: '/taxes-fees'
      preLoaderRoute: typeof TaxesFeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/styleguide': {
      id: '/styleguide'
      path: '/styleguide'
      fullPath: '/styleguide'
      preLoaderRoute: typeof StyleguideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms': {
      id: '/rooms'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof RoomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roles': {
      id: '/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof RolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/revenue-drilldown': {
      id: '/revenue-drilldown'
      path: '/revenue-drilldown'
      fullPath: '/revenue-drilldown'
      preLoaderRoute: typeof RevenueDrilldownRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/revenue': {
      id: '/revenue'
      path: '/revenue'
      fullPath: '/revenue'
      preLoaderRoute: typeof RevenueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservations': {
      id: '/reservations'
      path: '/reservations'
      fullPath: '/reservations'
      preLoaderRoute: typeof ReservationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registration-cards': {
      id: '/registration-cards'
      path: '/registration-cards'
      fullPath: '/registration-cards'
      preLoaderRoute: typeof RegistrationCardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rate-plans': {
      id: '/rate-plans'
      path: '/rate-plans'
      fullPath: '/rate-plans'
      preLoaderRoute: typeof RatePlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/property': {
      id: '/property'
      path: '/property'
      fullPath: '/property'
      preLoaderRoute: typeof PropertyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pos': {
      id: '/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof PosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pms-integrations': {
      id: '/pms-integrations'
      path: '/pms-integrations'
      fullPath: '/pms-integrations'
      preLoaderRoute: typeof PmsIntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages': {
      id: '/packages'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof PackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ota': {
      id: '/ota'
      path: '/ota'
      fullPath: '/ota'
      preLoaderRoute: typeof OtaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/one': {
      id: '/one'
      path: '/one'
      fullPath: '/one'
      preLoaderRoute: typeof OneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/masters': {
      id: '/masters'
      path: '/masters'
      fullPath: '/masters'
      preLoaderRoute: typeof MastersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loyalty': {
      id: '/loyalty'
      path: '/loyalty'
      fullPath: '/loyalty'
      preLoaderRoute: typeof LoyaltyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lost-found': {
      id: '/lost-found'
      path: '/lost-found'
      fullPath: '/lost-found'
      preLoaderRoute: typeof LostFoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads': {
      id: '/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof LeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/housekeeping': {
      id: '/housekeeping'
      path: '/housekeeping'
      fullPath: '/housekeeping'
      preLoaderRoute: typeof HousekeepingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotels': {
      id: '/hotels'
      path: '/hotels'
      fullPath: '/hotels'
      preLoaderRoute: typeof HotelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guests': {
      id: '/guests'
      path: '/guests'
      fullPath: '/guests'
      preLoaderRoute: typeof GuestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guest-requests': {
      id: '/guest-requests'
      path: '/guest-requests'
      fullPath: '/guest-requests'
      preLoaderRoute: typeof GuestRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups': {
      id: '/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof GroupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/front-desk': {
      id: '/front-desk'
      path: '/front-desk'
      fullPath: '/front-desk'
      preLoaderRoute: typeof FrontDeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corporate': {
      id: '/corporate'
      path: '/corporate'
      fullPath: '/corporate'
      preLoaderRoute: typeof CorporateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concierge': {
      id: '/concierge'
      path: '/concierge'
      fullPath: '/concierge'
      preLoaderRoute: typeof ConciergeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communications': {
      id: '/communications'
      path: '/communications'
      fullPath: '/communications'
      preLoaderRoute: typeof CommunicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/check-in': {
      id: '/check-in'
      path: '/check-in'
      fullPath: '/check-in'
      preLoaderRoute: typeof CheckInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/channel-manager': {
      id: '/channel-manager'
      path: '/channel-manager'
      fullPath: '/channel-manager'
      preLoaderRoute: typeof ChannelManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking-readiness': {
      id: '/booking-readiness'
      path: '/booking-readiness'
      fullPath: '/booking-readiness'
      preLoaderRoute: typeof BookingReadinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking-engine': {
      id: '/booking-engine'
      path: '/booking-engine'
      fullPath: '/booking-engine'
      preLoaderRoute: typeof BookingEngineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/availability': {
      id: '/availability'
      path: '/availability'
      fullPath: '/availability'
      preLoaderRoute: typeof AvailabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anomaly-monitor': {
      id: '/anomaly-monitor'
      path: '/anomaly-monitor'
      fullPath: '/anomaly-monitor'
      preLoaderRoute: typeof AnomalyMonitorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-insights': {
      id: '/ai-insights'
      path: '/ai-insights'
      fullPath: '/ai-insights'
      preLoaderRoute: typeof AiInsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-ons': {
      id: '/add-ons'
      path: '/add-ons'
      fullPath: '/add-ons'
      preLoaderRoute: typeof AddOnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity-timeline': {
      id: '/activity-timeline'
      path: '/activity-timeline'
      fullPath: '/activity-timeline'
      preLoaderRoute: typeof ActivityTimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activities': {
      id: '/activities'
      path: '/activities'
      fullPath: '/activities'
      preLoaderRoute: typeof ActivitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin/users': {
      id: '/superadmin/users'
      path: '/superadmin/users'
      fullPath: '/superadmin/users'
      preLoaderRoute: typeof SuperadminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin/tenants': {
      id: '/superadmin/tenants'
      path: '/superadmin/tenants'
      fullPath: '/superadmin/tenants'
      preLoaderRoute: typeof SuperadminTenantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin/subscriptions': {
      id: '/superadmin/subscriptions'
      path: '/superadmin/subscriptions'
      fullPath: '/superadmin/subscriptions'
      preLoaderRoute: typeof SuperadminSubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin/settings': {
      id: '/superadmin/settings'
      path: '/superadmin/settings'
      fullPath: '/superadmin/settings'
      preLoaderRoute: typeof SuperadminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin/roles': {
      id: '/superadmin/roles'
      path: '/superadmin/roles'
      fullPath: '/superadmin/roles'
      preLoaderRoute: typeof SuperadminRolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin/properties': {
      id: '/superadmin/properties'
      path: '/superadmin/properties'
      fullPath: '/superadmin/properties'
      preLoaderRoute: typeof SuperadminPropertiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin/products': {
      id: '/superadmin/products'
      path: '/superadmin/products'
      fullPath: '/superadmin/products'
      preLoaderRoute: typeof SuperadminProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin/manual': {
      id: '/superadmin/manual'
      path: '/superadmin/manual'
      fullPath: '/superadmin/manual'
      preLoaderRoute: typeof SuperadminManualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin/dashboard': {
      id: '/superadmin/dashboard'
      path: '/superadmin/dashboard'
      fullPath: '/superadmin/dashboard'
      preLoaderRoute: typeof SuperadminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/revenue/ai-dashboard': {
      id: '/revenue/ai-dashboard'
      path: '/ai-dashboard'
      fullPath: '/revenue/ai-dashboard'
      preLoaderRoute: typeof RevenueAiDashboardRouteImport
      parentRoute: typeof RevenueRoute
    }
    '/reservations/new': {
      id: '/reservations/new'
      path: '/new'
      fullPath: '/reservations/new'
      preLoaderRoute: typeof ReservationsNewRouteImport
      parentRoute: typeof ReservationsRoute
    }
    '/pos/menu': {
      id: '/pos/menu'
      path: '/menu'
      fullPath: '/pos/menu'
      preLoaderRoute: typeof PosMenuRouteImport
      parentRoute: typeof PosRoute
    }
    '/pos/kot': {
      id: '/pos/kot'
      path: '/kot'
      fullPath: '/pos/kot'
      preLoaderRoute: typeof PosKotRouteImport
      parentRoute: typeof PosRoute
    }
    '/pos/inventory': {
      id: '/pos/inventory'
      path: '/inventory'
      fullPath: '/pos/inventory'
      preLoaderRoute: typeof PosInventoryRouteImport
      parentRoute: typeof PosRoute
    }
    '/pos/billing': {
      id: '/pos/billing'
      path: '/billing'
      fullPath: '/pos/billing'
      preLoaderRoute: typeof PosBillingRouteImport
      parentRoute: typeof PosRoute
    }
    '/housekeeping/mobile': {
      id: '/housekeeping/mobile'
      path: '/mobile'
      fullPath: '/housekeeping/mobile'
      preLoaderRoute: typeof HousekeepingMobileRouteImport
      parentRoute: typeof HousekeepingRoute
    }
    '/dashboard/multi-property': {
      id: '/dashboard/multi-property'
      path: '/dashboard/multi-property'
      fullPath: '/dashboard/multi-property'
      preLoaderRoute: typeof DashboardMultiPropertyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/channel-manager/sync-logs': {
      id: '/channel-manager/sync-logs'
      path: '/sync-logs'
      fullPath: '/channel-manager/sync-logs'
      preLoaderRoute: typeof ChannelManagerSyncLogsRouteImport
      parentRoute: typeof ChannelManagerRoute
    }
    '/channel-manager/room-mapping': {
      id: '/channel-manager/room-mapping'
      path: '/room-mapping'
      fullPath: '/channel-manager/room-mapping'
      preLoaderRoute: typeof ChannelManagerRoomMappingRouteImport
      parentRoute: typeof ChannelManagerRoute
    }
    '/channel-manager/room-content': {
      id: '/channel-manager/room-content'
      path: '/room-content'
      fullPath: '/channel-manager/room-content'
      preLoaderRoute: typeof ChannelManagerRoomContentRouteImport
      parentRoute: typeof ChannelManagerRoute
    }
    '/channel-manager/revenue': {
      id: '/channel-manager/revenue'
      path: '/revenue'
      fullPath: '/channel-manager/revenue'
      preLoaderRoute: typeof ChannelManagerRevenueRouteImport
      parentRoute: typeof ChannelManagerRoute
    }
    '/channel-manager/restrictions': {
      id: '/channel-manager/restrictions'
      path: '/restrictions'
      fullPath: '/channel-manager/restrictions'
      preLoaderRoute: typeof ChannelManagerRestrictionsRouteImport
      parentRoute: typeof ChannelManagerRoute
    }
    '/channel-manager/reservations': {
      id: '/channel-manager/reservations'
      path: '/reservations'
      fullPath: '/channel-manager/reservations'
      preLoaderRoute: typeof ChannelManagerReservationsRouteImport
      parentRoute: typeof ChannelManagerRoute
    }
    '/channel-manager/rates': {
      id: '/channel-manager/rates'
      path: '/rates'
      fullPath: '/channel-manager/rates'
      preLoaderRoute: typeof ChannelManagerRatesRouteImport
      parentRoute: typeof ChannelManagerRoute
    }
    '/channel-manager/rate-plans': {
      id: '/channel-manager/rate-plans'
      path: '/rate-plans'
      fullPath: '/channel-manager/rate-plans'
      preLoaderRoute: typeof ChannelManagerRatePlansRouteImport
      parentRoute: typeof ChannelManagerRoute
    }
    '/channel-manager/property-content': {
      id: '/channel-manager/property-content'
      path: '/property-content'
      fullPath: '/channel-manager/property-content'
      preLoaderRoute: typeof ChannelManagerPropertyContentRouteImport
      parentRoute: typeof ChannelManagerRoute
    }
    '/channel-manager/multi-property': {
      id: '/channel-manager/multi-property'
      path: '/multi-property'
      fullPath: '/channel-manager/multi-property'
      preLoaderRoute: typeof ChannelManagerMultiPropertyRouteImport
      parentRoute: typeof ChannelManagerRoute
    }
    '/channel-manager/inventory': {
      id: '/channel-manager/inventory'
      path: '/inventory'
      fullPath: '/channel-manager/inventory'
      preLoaderRoute: typeof ChannelManagerInventoryRouteImport
      parentRoute: typeof ChannelManagerRoute
    }
    '/channel-manager/incidents': {
      id: '/channel-manager/incidents'
      path: '/incidents'
      fullPath: '/channel-manager/incidents'
      preLoaderRoute: typeof ChannelManagerIncidentsRouteImport
      parentRoute: typeof ChannelManagerRoute
    }
    '/channel-manager/images': {
      id: '/channel-manager/images'
      path: '/images'
      fullPath: '/channel-manager/images'
      preLoaderRoute: typeof ChannelManagerImagesRouteImport
      parentRoute: typeof ChannelManagerRoute
    }
    '/channel-manager/connections': {
      id: '/channel-manager/connections'
      path: '/connections'
      fullPath: '/channel-manager/connections'
      preLoaderRoute: typeof ChannelManagerConnectionsRouteImport
      parentRoute: typeof ChannelManagerRoute
    }
    '/channel-manager/availability': {
      id: '/channel-manager/availability'
      path: '/availability'
      fullPath: '/channel-manager/availability'
      preLoaderRoute: typeof ChannelManagerAvailabilityRouteImport
      parentRoute: typeof ChannelManagerRoute
    }
    '/channel-manager/analytics': {
      id: '/channel-manager/analytics'
      path: '/analytics'
      fullPath: '/channel-manager/analytics'
      preLoaderRoute: typeof ChannelManagerAnalyticsRouteImport
      parentRoute: typeof ChannelManagerRoute
    }
    '/analytics/executive': {
      id: '/analytics/executive'
      path: '/analytics/executive'
      fullPath: '/analytics/executive'
      preLoaderRoute: typeof AnalyticsExecutiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin/tenants/new': {
      id: '/superadmin/tenants/new'
      path: '/new'
      fullPath: '/superadmin/tenants/new'
      preLoaderRoute: typeof SuperadminTenantsNewRouteImport
      parentRoute: typeof SuperadminTenantsRoute
    }
  }
}

interface ChannelManagerRouteChildren {
  ChannelManagerAnalyticsRoute: typeof ChannelManagerAnalyticsRoute
  ChannelManagerAvailabilityRoute: typeof ChannelManagerAvailabilityRoute
  ChannelManagerConnectionsRoute: typeof ChannelManagerConnectionsRoute
  ChannelManagerImagesRoute: typeof ChannelManagerImagesRoute
  ChannelManagerIncidentsRoute: typeof ChannelManagerIncidentsRoute
  ChannelManagerInventoryRoute: typeof ChannelManagerInventoryRoute
  ChannelManagerMultiPropertyRoute: typeof ChannelManagerMultiPropertyRoute
  ChannelManagerPropertyContentRoute: typeof ChannelManagerPropertyContentRoute
  ChannelManagerRatePlansRoute: typeof ChannelManagerRatePlansRoute
  ChannelManagerRatesRoute: typeof ChannelManagerRatesRoute
  ChannelManagerReservationsRoute: typeof ChannelManagerReservationsRoute
  ChannelManagerRestrictionsRoute: typeof ChannelManagerRestrictionsRoute
  ChannelManagerRevenueRoute: typeof ChannelManagerRevenueRoute
  ChannelManagerRoomContentRoute: typeof ChannelManagerRoomContentRoute
  ChannelManagerRoomMappingRoute: typeof ChannelManagerRoomMappingRoute
  ChannelManagerSyncLogsRoute: typeof ChannelManagerSyncLogsRoute
}

const ChannelManagerRouteChildren: ChannelManagerRouteChildren = {
  ChannelManagerAnalyticsRoute: ChannelManagerAnalyticsRoute,
  ChannelManagerAvailabilityRoute: ChannelManagerAvailabilityRoute,
  ChannelManagerConnectionsRoute: ChannelManagerConnectionsRoute,
  ChannelManagerImagesRoute: ChannelManagerImagesRoute,
  ChannelManagerIncidentsRoute: ChannelManagerIncidentsRoute,
  ChannelManagerInventoryRoute: ChannelManagerInventoryRoute,
  ChannelManagerMultiPropertyRoute: ChannelManagerMultiPropertyRoute,
  ChannelManagerPropertyContentRoute: ChannelManagerPropertyContentRoute,
  ChannelManagerRatePlansRoute: ChannelManagerRatePlansRoute,
  ChannelManagerRatesRoute: ChannelManagerRatesRoute,
  ChannelManagerReservationsRoute: ChannelManagerReservationsRoute,
  ChannelManagerRestrictionsRoute: ChannelManagerRestrictionsRoute,
  ChannelManagerRevenueRoute: ChannelManagerRevenueRoute,
  ChannelManagerRoomContentRoute: ChannelManagerRoomContentRoute,
  ChannelManagerRoomMappingRoute: ChannelManagerRoomMappingRoute,
  ChannelManagerSyncLogsRoute: ChannelManagerSyncLogsRoute,
}

const ChannelManagerRouteWithChildren = ChannelManagerRoute._addFileChildren(
  ChannelManagerRouteChildren,
)

interface HousekeepingRouteChildren {
  HousekeepingMobileRoute: typeof HousekeepingMobileRoute
}

const HousekeepingRouteChildren: HousekeepingRouteChildren = {
  HousekeepingMobileRoute: HousekeepingMobileRoute,
}

const HousekeepingRouteWithChildren = HousekeepingRoute._addFileChildren(
  HousekeepingRouteChildren,
)

interface PosRouteChildren {
  PosBillingRoute: typeof PosBillingRoute
  PosInventoryRoute: typeof PosInventoryRoute
  PosKotRoute: typeof PosKotRoute
  PosMenuRoute: typeof PosMenuRoute
}

const PosRouteChildren: PosRouteChildren = {
  PosBillingRoute: PosBillingRoute,
  PosInventoryRoute: PosInventoryRoute,
  PosKotRoute: PosKotRoute,
  PosMenuRoute: PosMenuRoute,
}

const PosRouteWithChildren = PosRoute._addFileChildren(PosRouteChildren)

interface ReservationsRouteChildren {
  ReservationsNewRoute: typeof ReservationsNewRoute
}

const ReservationsRouteChildren: ReservationsRouteChildren = {
  ReservationsNewRoute: ReservationsNewRoute,
}

const ReservationsRouteWithChildren = ReservationsRoute._addFileChildren(
  ReservationsRouteChildren,
)

interface RevenueRouteChildren {
  RevenueAiDashboardRoute: typeof RevenueAiDashboardRoute
}

const RevenueRouteChildren: RevenueRouteChildren = {
  RevenueAiDashboardRoute: RevenueAiDashboardRoute,
}

const RevenueRouteWithChildren =
  RevenueRoute._addFileChildren(RevenueRouteChildren)

interface SuperadminTenantsRouteChildren {
  SuperadminTenantsNewRoute: typeof SuperadminTenantsNewRoute
}

const SuperadminTenantsRouteChildren: SuperadminTenantsRouteChildren = {
  SuperadminTenantsNewRoute: SuperadminTenantsNewRoute,
}

const SuperadminTenantsRouteWithChildren =
  SuperadminTenantsRoute._addFileChildren(SuperadminTenantsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivitiesRoute: ActivitiesRoute,
  ActivityTimelineRoute: ActivityTimelineRoute,
  AddOnsRoute: AddOnsRoute,
  AiInsightsRoute: AiInsightsRoute,
  AnomalyMonitorRoute: AnomalyMonitorRoute,
  AuditRoute: AuditRoute,
  AvailabilityRoute: AvailabilityRoute,
  BillingRoute: BillingRoute,
  BookingEngineRoute: BookingEngineRoute,
  BookingReadinessRoute: BookingReadinessRoute,
  ChannelManagerRoute: ChannelManagerRouteWithChildren,
  CheckInRoute: CheckInRoute,
  CommunicationsRoute: CommunicationsRoute,
  ConciergeRoute: ConciergeRoute,
  CorporateRoute: CorporateRoute,
  FeedbackRoute: FeedbackRoute,
  FrontDeskRoute: FrontDeskRoute,
  GroupsRoute: GroupsRoute,
  GuestRequestsRoute: GuestRequestsRoute,
  GuestsRoute: GuestsRoute,
  HotelsRoute: HotelsRoute,
  HousekeepingRoute: HousekeepingRouteWithChildren,
  LeadsRoute: LeadsRoute,
  LoginRoute: LoginRoute,
  LostFoundRoute: LostFoundRoute,
  LoyaltyRoute: LoyaltyRoute,
  MaintenanceRoute: MaintenanceRoute,
  MastersRoute: MastersRoute,
  NotificationsRoute: NotificationsRoute,
  OnboardingRoute: OnboardingRoute,
  OneRoute: OneRoute,
  OtaRoute: OtaRoute,
  PackagesRoute: PackagesRoute,
  PaymentsRoute: PaymentsRoute,
  PmsIntegrationsRoute: PmsIntegrationsRoute,
  PosRoute: PosRouteWithChildren,
  PricingRoute: PricingRoute,
  PropertyRoute: PropertyRoute,
  RatePlansRoute: RatePlansRoute,
  RegistrationCardsRoute: RegistrationCardsRoute,
  ReportsRoute: ReportsRoute,
  ReservationsRoute: ReservationsRouteWithChildren,
  RevenueRoute: RevenueRouteWithChildren,
  RevenueDrilldownRoute: RevenueDrilldownRoute,
  RolesRoute: RolesRoute,
  RoomsRoute: RoomsRoute,
  SearchRoute: SearchRoute,
  ServicesRoute: ServicesRoute,
  SettingsRoute: SettingsRoute,
  StaffRoute: StaffRoute,
  StyleguideRoute: StyleguideRoute,
  TasksRoute: TasksRoute,
  TaxesFeesRoute: TaxesFeesRoute,
  TransportRoute: TransportRoute,
  UsersRoute: UsersRoute,
  WebsiteBuilderRoute: WebsiteBuilderRoute,
  AnalyticsExecutiveRoute: AnalyticsExecutiveRoute,
  DashboardMultiPropertyRoute: DashboardMultiPropertyRoute,
  SuperadminDashboardRoute: SuperadminDashboardRoute,
  SuperadminManualRoute: SuperadminManualRoute,
  SuperadminProductsRoute: SuperadminProductsRoute,
  SuperadminPropertiesRoute: SuperadminPropertiesRoute,
  SuperadminRolesRoute: SuperadminRolesRoute,
  SuperadminSettingsRoute: SuperadminSettingsRoute,
  SuperadminSubscriptionsRoute: SuperadminSubscriptionsRoute,
  SuperadminTenantsRoute: SuperadminTenantsRouteWithChildren,
  SuperadminUsersRoute: SuperadminUsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
